car_collection/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import uuid
from datetime import datetime

from werkzeug.security import check_password_hash, generate_password_hash

import secrets

from flask_login import UserMixin, LoginManager

from flask_marshmallow import Marshmallow
db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key = True)
    first_name = db.Column(db.String(150), nullable = True, default = "")
    last_name = db.Column(db.String(150), nullable = True, default= "")
    email = db.Column(db.String(150), nullable = False)
    password = db.Column(db.String, nullable = True, default = "")
    token = db.Column(db.String, default = "", unique = True)
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)
    g_auth_verify = db.Column(db.Boolean, default = False)
    
    def __init__(self,email, first_name ="", last_name = "", password = "", token = "", g_auth_verify = False):
        self.id = self.get_id()
        self.first_name = first_name
        self.last_name = last_name
        self.password = self.get_password(password)
        self.email = email
        self.token = self.get_token(24)
        self.g_auth_verify = g_auth_verify
                
    def get_token(self,number):
        return secrets.token_hex(number)
    def get_id(self):
        return str(uuid.uuid4())
        
    def get_password(self,password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash
    
    def __repr__(self):
        return f"User {self.email} added to db!"
    
    
class Car(db.Model):
    id = db.Column(db.String, primary_key = True)
    name = db.Column(db.String(150))
    make = db.Column(db.String(100))
    model = db.Column(db.String(100))
    year = db.Column(db.Integer())
    # user_token = db.Column(db.String, db.ForeignKey('User.token'))
    
    def __init__(self,name,make,model,year):
        self.id = self.get_id()
        self.name = name
        self.make = make
        self.model = model
        self.year = year
        # self.user_token = user_token
        
    def __repr__(self):
        return f"The following car has been added {self.name}"
    
    def get_id(self):
        return(secrets.token_urlsafe())
    
class CarSchema(ma.Schema):
    class Meta: 
        fields = ['id','name','make','model','year']

car_schema = CarSchema()
cars_schema = CarSchema(many = True)
    

car_collection/__init__.py
from flask import Flask
from .main_site.routes import main
from .auth.routes import auth
from .api.routes import api
from config import Config

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

from .models import db as root_db
from .models import login_manager, ma

from flask_marshmallow import Marshmallow

from flask_cors import CORS

from car_collection.helpers import JSONEncoder

app = Flask(__name__)

app.register_blueprint(main)
app.register_blueprint(api)
app.register_blueprint(auth)
app.config.from_object(Config)

root_db.init_app(app)

migrate = Migrate(app, root_db)

login_manager.init_app(app)
login_manager.login_view = 'auth.signin'

ma.init_app(app)

app.json_encoder = JSONEncoder

CORS(app)

car_collection/api/routes.py
from flask import Blueprint, request, jsonify
from car_collection.helpers import token_required
from car_collection.models import db, User, Car, car_schema, cars_schema

api = Blueprint('api', __name__, url_prefix = '/api')

@api.route('/test')
@token_required
def test(current_user_token):
    return {'User' : 'Value'}

@api.route('/cars', methods = ['POST'])
@token_required
def create_car(current_user_token):
    name = request.json['name']
    make = request.json['make']
    model = request.json['model']
    year = request.json['year']
    user_token = current_user_token.token
    
    print(f"Testing: {current_user_token.token}")
    
    car = Car(name, make, model, year, user_token = user_token)
    
    db.session.add(car)
    db.session.commit()
    res = car_schema.dump(car)
    
    return jsonify(res)

@api.route('/cars', methods = ['GET'])
@token_required
def get_cars(current_user_token):
    own = current_user_token.token
    cars = Car.query.filter_by(user_token = own).all()
    res = cars_schema.dump(cars)
    
    return jsonify(res)

@api.route('/cars<id>', methods = ['GET'])
@token_required
def get_car(current_user_token, id):
    own = current_user_token.token
    if own == current_user_token.token:
        car = Car.query.get(id)
        res = car_schema.dump(car)
        return jsonify(res)
    
    else:
        return jsonify('message : Valid Token Not Received'), 401
    
@api.route('/cars/<id>', methods = ['POST', 'PUT'])
@token_required
def update_car(current_user_token, id):
    car = car.query.get(id)
    
    car.name = request.json['name']
    car.make = request.json['make']
    car.model = request.json['model']
    car.year = request.json['year']
    car.user_token = current_user_token.token
    
    db.session.commit()
    
    res = car_schema.dump(car)
    
    return jsonify(res)

@api.route('/cars/<id>', methods = ['DELETE'])
@token_required
def delete_car(current_user_token, id):
    car = car.query.get(id)
    
    db.session.delete(car)
    
    db.session.commit()
    
    res = car_schema.dump(car)
    
    return jsonify(res)
    
    

car_collection/main_site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

main = Blueprint('main',__name__,template_folder='main_templates')

@main.route('/')
def home():
    return render_template('index.html')

@main.route('/profile')
@login_required
def profile():
    return render_template('prof.html')

car_collection/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Car Collection</title>
</head>
<body>
    <nav>
        <ul id="nav-list">
            <a href="{{url_for('main.home')}}">
                <li>Car Collection</li>
            </a>
            <a href="{{url_for('main.profile')}}">
                <li>
                    Car Profile
                </li>
            </a>
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('auth.logout') }}">
                <li>Log Out</li>
            </a>
            {% else %}
            <a href="{{url_for('auth.signin')}}">
                <li>
                    Sign in
                </li>
            </a>
            <a href="{{url_for('auth.signup')}}">
                <li>
                    Sign up
                </li>
            </a>      
            {% endif %}      
        </ul>
    </nav>

    {% block content %}
    {% endblock content%}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

car_collection/templates/sign-in-form.html
<form method = "POST">
    {{form.hidden_tag()}}
    <div class="form-group">
        <fieldset id="email">
            {{form.email.label}}
            {{form.email(class="form-control", placeholder = "Email Address")}}
        </fieldset>
        <fieldset id="pass-field">
            {{form.password.label}}
            {{form.password(class="form-control",placeholder = "Password")}}
        </fieldset>

        {{form.submit(class="btn btn-primary btn-block")}}
    </div>
</form>

car_collection/templates/sign-up-form.html
<form method = "POST">
    {{form.hidden_tag()}}
    <div class="form-group">
        <fieldset id="email">
            {{form.email.label}}
            {{form.email(class="form-control", placeholder = "Email Address")}}
        </fieldset>
        <fieldset id="pass-field">
            {{form.password.label}}
            {{form.password(class="form-control",placeholder = "Password")}}
        </fieldset>
        <fieldset id="fav-car">
            {{form.favorite_car.label}}
            {{form.favorite_car(class="form-control",placeholder = "Enter Favorite Car(optional)")}}
        </fieldset>

        {{form.submit(class="btn btn-primary btn-block")}}
    </div>
</form>